steps:

- id: "Rodando docker-compose"
  name: 'gcr.io/codeeducation-test-272417/docker-compose:1.24.0'
  args: ['-f','docker-compose.cloudbuild.yaml','up','-d']


- id: "Rodando docker-compose ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']
