steps:

- id: "Ridando docker-compose"
  name: 'gcr.io/codeeducation-test-272417/docker-compose'
  args: ['-f','docker-compose.cloudbuild.yaml','up','-d']


- id: "Rodando docker-compose ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']
